from datetime import datetime, timezone

# Keep legacy naive-UTC wire timestamps until a separately approved format migration.
from typing import List, Optional
from pydantic import BaseModel, Field


class Patch(BaseModel):
    """Represents a code patch generated by the AI."""
    patch_id: str = Field(..., description="Unique identifier for the patch")
    description: str = Field(..., description="Human-readable description of the patch")
    diff: str = Field(..., description="Unified diff format patch content")
    affected_files: List[str] = Field(default_factory=list, description="List of files affected by this patch")
    validation_warnings: List[str] = Field(default_factory=list, description="Warnings from patch validation")
    risk_level: str = Field(..., description="Risk level: low, medium, high")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc).replace(tzinfo=None), description="Timestamp of patch creation")